name: logistisen

services:
  logistisen_db:
    image: 'postgres:16'
    container_name: logistisen_db_container
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
    environment:
      - 'POSTGRES_DB=logistisen_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  api_auth:
    build:
      context: API_Authentication
      dockerfile: Dockerfile
    container_name: API_Authentication
    environment:
      - 'SECRET_KEY=c3Q2PO9y0XjN6Twk5u1MSyVIVpTlYRi5'
      - 'BYPASS_TOKEN=v2Fq5EoogcM0F7L2dtvZ9KZNaYpdfdx7'
    ports:
      - "5050:5050"
    depends_on:
      - logistisen_db
    volumes:
      - ./API_Authentication:/API_Authentication:ro
  api_stock:
    build:
      context: API_Stock
      dockerfile: Dockerfile
    container_name: API_Stock
    environment:
      - 'SECRET_KEY=c3Q2PO9y0XjN6Twk5u1MSyVIVpTlYRi5'
      - 'BYPASS_TOKEN=v2Fq5EoogcM0F7L2dtvZ9KZNaYpdfdx7'
    ports:
      - "8000:8000"
    depends_on:
      - logistisen_db
    volumes:
      - ./API_Stock:/API_Stock:ro
  api_event:
    build:
      context: API_Event
      dockerfile: Dockerfile
    container_name: API_Event
    environment:
      - 'SECRET_KEY=c3Q2PO9y0XjN6Twk5u1MSyVIVpTlYRi5'
      - 'BYPASS_TOKEN=v2Fq5EoogcM0F7L2dtvZ9KZNaYpdfdx7'
    ports:
      - "5000:5000"
    depends_on:
      - logistisen_db
    volumes:
      - ./API_Event:/API_Event:ro
  service_logistique:
    build:
      context: Service_Logistique
      dockerfile: Dockerfile
    container_name: Service_Logistique
    environment:
      - 'BYPASS_TOKEN=v2Fq5EoogcM0F7L2dtvZ9KZNaYpdfdx7'
    ports:
      - "5200:5200"
    depends_on:
      - logistisen_db
      - api_stock
      - api_event
      - api_auth
    volumes:
      - ./Service_Logistique:/Service_Logistique:ro