version: '3'
name: logistisen

services:
  logistisen_db:
    image: 'postgres:16'
    container_name: logistisen_db_container
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
    environment:
      - 'POSTGRES_DB=logistisen_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  api_auth:
    build:
      context: .
      dockerfile: API_Authentication/Dockerfile
    container_name: API_Authentication
    environment:
      -SECRET_KEY=c3Q2PO9y0XjN6Twk5u1MSyVIVpTlYRi5
    ports:
      - "5050:5050"
    depends_on:
      - logistisen_db
    volumes:
      - .:/API_Authentication:ro